'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useStore} from './store';
import {PageHead,Card,Field,Btn} from './ui';

export default function Settings(){
  const {state,saveSettingsApi,updateLogoApi,isLive}=useStore();
  const [form,setForm]=useState({...state.settings}),[logo,setLogo]=useState<File|null>(null),[saving,setSaving]=useState(false);
  const set=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));
  async function save(){setSaving(true);const ok=await saveSettingsApi(form,logo||undefined);setSaving(false);if(ok)setLogo(null);}
  return <><PageHead title="Company settings" description="These details appear throughout the workspace and on issued invoices. Until setup is complete, the application displays Billing Software." actions={<Link className="btn secondary" href="/templates">Invoice templates</Link>}/><Card title="Business identity"><div className="form-body form-grid"><Field label="Company / business name"><input required value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Your registered or trading name"/></Field><Field label="Phone"><input required value={form.phone} onChange={e=>set('phone',e.target.value)}/></Field><Field label="Email"><input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="GSTIN"><input value={form.gst} onChange={e=>set('gst',e.target.value.toUpperCase())} placeholder="Enter later if applicable"/></Field><div className="full"><Field label="Business address"><textarea required value={form.address} onChange={e=>set('address',e.target.value)}/></Field></div><Field label="State"><input value={form.state||''} onChange={e=>set('state',e.target.value)} placeholder="Tamil Nadu"/></Field><Field label="State code"><input value={form.stateCode||''} onChange={e=>set('stateCode',e.target.value)} maxLength={2}/></Field><Field label="PIN code"><input value={form.postalCode||''} onChange={e=>set('postalCode',e.target.value)} maxLength={6}/></Field><Field label="Company logo"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setLogo(e.target.files?.[0]||null)}/></Field>{form.logo&&<div className="full"><img src={form.logo} alt="Current company logo" style={{maxWidth:180,maxHeight:90,objectFit:'contain'}}/><Btn secondary onClick={async()=>{await updateLogoApi(null);setForm(current=>({...current,logo:''}));}}>Remove logo</Btn></div>}</div></Card><Card title="Invoice payment details"><div className="form-body form-grid"><Field label="Bank name"><input value={form.bank} onChange={e=>set('bank',e.target.value)}/></Field><Field label="Account number"><input value={form.account} onChange={e=>set('account',e.target.value)}/></Field><Field label="IFSC"><input value={form.ifsc} onChange={e=>set('ifsc',e.target.value.toUpperCase())}/></Field><div className="full"><Field label="Invoice declaration"><textarea value={form.declaration} onChange={e=>set('declaration',e.target.value)}/></Field></div></div></Card><Card title="Data separation"><div className="settings-copy"><p>{isLive?'This signed-in company uses its own tenant-isolated MongoDB records.':'Sign in from Company account to save this tenant’s data to MongoDB Atlas.'}</p><p className="muted">Each company configures its own identity, customers, products, services, invoices, templates, print jobs and reports.</p></div></Card><div className="form-actions"><Btn disabled={saving} onClick={save}>{saving?'Saving…':'Save company settings'}</Btn></div></>;
}
