import {supplyReferences} from './supply';
import {purchaseLineBalances,allocatePayment} from './settlement';
import {assertOpen} from './closing';
import {State,Bill,Purchase,Payment,Reservation,ReturnRecord,Product,Job,TODAY,uid,roundedTotal,balance,available,activeReservation,accountBalance} from './domain';
function clone(s:State){return structuredClone(s);}
function check(ok:unknown,message:string):asserts ok{if(!ok)throw new Error(message);}
function log(s:State,action:string,detail:string){s.audit.unshift({id:uid('LOG'),action,detail});}
function move(s:State,p:Product,qty:number,reason:string,reference:string,date=TODAY){p.stock+=qty;s.movements.unshift({id:uid('MOV'),date,productId:p.id,qty,reason,reference});}
function validateLines(b:Bill|Purchase){check(b.lines.length,'Add at least one item.');b.lines.forEach(l=>{check(l.name.trim(),'Every line needs a description.');check(Number.isInteger(l.qty)&&l.qty>0,'Quantity must be a positive whole number.');check(Number.isFinite(l.rate)&&l.rate>=0,'Rate cannot be negative.');check(Number.isFinite(l.discount)&&l.discount>=0&&l.discount<=(l.discountType==='Amount'?l.qty*l.rate:100),'Discount cannot exceed the line value (or 100%).');check(Number.isFinite(l.tax)&&l.tax>=0&&l.tax<=100,'Enter a valid tax rate.');});}
export function issueBill(state:State,b:Bill):State{
  if(b.kind!=='Quotation')assertOpen(state,b.date);
  check(b.date<=TODAY&&b.due>=b.date,'Check the document date and due date.');
  validateLines(b);
  check(state.customers.some(c=>c.id===b.customerId),'Select a customer.');
  check(!state.bills.some(x=>x.id===b.id),'That document number already exists.');
  const s=clone(state);
  if(b.kind==='Sale'){
    const seen=new Set<string>();
    for(const l of b.lines){
      if(!l.productId)continue;
      const p=s.products.find(x=>x.id===l.productId);
      check(p,'Product no longer exists.');
      check(!seen.has(p.id),'Combine duplicate product rows into one quantity.');
      seen.add(p.id);
    }
  }
  s.bills.unshift({
    ...b,
    customerSnapshot:structuredClone(s.customers.find(c=>c.id===b.customerId)!),
    shopSnapshot:structuredClone(s.settings),
    status:b.kind==='Quotation'?b.status:'Issued'
  });
  if(b.sourceId)s.bills=s.bills.map(x=>x.id===b.sourceId?{...x,status:'Converted'}:x);
  log(s,b.kind==='Quotation'?'Quotation saved':'Invoice issued',b.id);
  return s;
}
export function addPayment(state:State,p:Payment):State{assertOpen(state,p.date);check(Number.isFinite(p.amount)&&p.amount>0,'Enter an amount greater than zero.');check(p.date&&p.date<=TODAY,'Payment date cannot be after the demo business date.');check(['Cash','Bank account'].includes(p.account),'Select a valid account.');if(p.direction==='Transfer')check(p.toAccount&&['Cash','Bank account'].includes(p.toAccount)&&p.toAccount!==p.account,'Choose different source and destination accounts.');if(p.direction!=='In')check(p.amount<=accountBalance(state,p.account,p.date),'This account has insufficient funds on the selected date.');if(p.purpose==='Customer payment'||p.purpose==='Supplier payment'){const record=p.purpose==='Customer payment'?state.bills.find(b=>b.id===p.reference&&b.kind!=='Quotation'&&b.status==='Issued'):state.purchases.find(b=>b.id===p.reference);check(record,'Select a valid outstanding bill.');check(p.date>=record.date,'Payment cannot be before the bill date.');check(p.amount<=balance(state,record)+0.001,'Payment exceeds the remaining bill balance.');}if(p.purpose==='Supplier payment'){const bill=state.purchases.find(b=>b.id===p.reference)!;const allocations=p.allocations?.length?p.allocations:allocatePayment(state,bill,p.amount);check(Math.abs(allocations.reduce((a,x)=>a+x.amount,0)-p.amount)<0.01,'Product allocation total must match payment.');const dues=purchaseLineBalances(state,bill);check(new Set(allocations.map(a=>a.productId)).size===allocations.length,'Do not repeat a product allocation.');check(allocations.every(a=>a.amount>0&&a.amount<=(dues.find(d=>d.productId===a.productId)?.due??-1)+0.001),'A product payment exceeds its unpaid amount.');p={...p,allocations};}const s=clone(state);s.payments.unshift(p);log(s,'Payment recorded',`${p.reference} · ${p.amount} · ${p.account}`);return s;}
export function receivePurchase(state:State,b:Purchase):State{assertOpen(state,b.date);validateLines(b);check(state.suppliers.some(x=>x.id===b.supplierId),'Select a supplier.');const existing=state.purchases.find(x=>x.id===b.id);check(existing?.status!=='Received','This purchase has already been received.');const s=clone(state);const seen=new Set<string>();for(const l of b.lines){const p=s.products.find(x=>x.id===l.productId);check(p,'Every purchase line must select an inventory product.');check(!seen.has(p.id),'Combine duplicate product rows.');seen.add(p.id);const tracked=['Laptops','Monitors','Prebuilt PCs','Printers'].includes(p.category)||p.serials.length>0;if(tracked){check(l.serials.length===l.qty&&new Set(l.serials).size===l.qty,`${p.name}: enter ${l.qty} unique serial number(s).`);const all=s.products.flatMap(x=>x.serials).concat(s.warranties.map(w=>w.serial));check(l.serials.every(n=>n.trim()&&!all.includes(n)),`${p.name}: a serial number already exists.`);p.serials.push(...l.serials);}move(s,p,l.qty,'Purchase received',b.id,b.date);p.cost=b.inclusive?l.rate:l.rate*(1+l.tax/100);p.supplier=b.supplierId;}s.purchases=existing?s.purchases.map(p=>p.id===b.id?{...b,date:p.date,receivedDate:b.date,status:'Received'}:p):[{...b,receivedDate:b.date,status:'Received'},...s.purchases];log(s,'Purchase received',b.id);return s;}
export function reserveStock(state:State,r:Reservation):State{const p=state.products.find(x=>x.id===r.productId);check(p,'Select a product.');check(state.customers.some(c=>c.id===r.customerId),'Select a customer.');check(Number.isInteger(r.qty)&&r.qty>0&&r.qty<=available(state,p),'Reservation exceeds available stock.');check(r.expires>=TODAY,'Choose today or a future expiry date.');if(p.serials.length){check(r.serials.length===r.qty&&new Set(r.serials).size===r.qty,'Select a unique serial for each reserved unit.');const held=state.reservations.filter(activeReservation).flatMap(x=>x.serials);check(r.serials.every(n=>p.serials.includes(n)&&!held.includes(n)),'A selected serial is already reserved.');}const s=clone(state);s.reservations.unshift(r);log(s,'Stock reserved',`${r.qty} × ${p.name}`);return s;}
export function consumePart(state:State,jobId:string,productId:string,qty:number):State{assertOpen(state,TODAY);const p=state.products.find(x=>x.id===productId);check(p,'Choose a product.');check(Number.isInteger(qty)&&qty>0&&qty<=available(state,p),'Not enough unreserved parts in stock.');check(!p.serials.length,'Use an untracked repair component here; serialized units are handled through sales.');const s=clone(state),job=s.jobs.find(j=>j.id===jobId);check(job&&job.status!=='Delivered','This job is not open.');check(!s.bills.some(b=>b.jobId===jobId&&b.kind!=='Quotation'),'Parts cannot be added after this job has been invoiced.');job.parts.push({productId,qty});move(s,s.products.find(x=>x.id===productId)!,-qty,'Service part',jobId);log(s,'Part used',jobId);return s;}
export function processReturn(state:State,r:ReturnRecord,refund:number,account:string):State{assertOpen(state,r.date);const original=r.type==='Customer'?state.bills.find(b=>b.id===r.reference&&b.kind==='Sale'&&b.status==='Issued'):state.purchases.find(b=>b.id===r.reference&&b.status==='Received');check(original,'Select an issued sale or received purchase.');const line=original.lines.find(l=>l.productId===r.productId);check(line,'Select a product from the original document.');const returned=state.returns.filter(x=>x.reference===r.reference&&x.productId===r.productId).reduce((a,x)=>a+x.qty,0);check(Number.isInteger(r.qty)&&r.qty>0&&r.qty<=line.qty-returned,'Return quantity exceeds the remaining returnable quantity.');const per=roundedTotal({lines:[line],inclusive:original.inclusive})/line.qty;check(r.amount>0&&r.amount<=per*r.qty+0.02,'Adjustment exceeds the original value of the returned items.');check(r.reason.trim(),'Enter a return reason.');if(line.serials.length){const already=state.returns.filter(x=>x.reference===r.reference).flatMap(x=>x.serials);check(r.serials.length===r.qty&&new Set(r.serials).size===r.qty&&r.serials.every(n=>line.serials.includes(n)&&!already.includes(n)),'Select the original serial number(s) not already returned.');}const outstanding=balance(state,original);const maxRefund=Math.max(0,r.amount-outstanding);check(refund>=0&&refund<=maxRefund+0.01,`Refund cannot exceed ${maxRefund.toFixed(2)} after adjusting outstanding dues.`);if(refund>0&&r.type==='Customer')check(refund<=accountBalance(state,account),'Not enough funds for refund.');const s=clone(state),p=s.products.find(x=>x.id===r.productId);check(p,'Product is missing.');if(r.type==='Supplier'){check(r.qty<=available(s,p),'Not enough unreserved stock for supplier return.');if(p.serials.length)check(r.serials.every(n=>p.serials.includes(n)),'Returned serials are not in stock.');p.serials=p.serials.filter(n=>!r.serials.includes(n));move(s,p,-r.qty,'Supplier return',r.id,r.date);}else{if(r.disposition==='Restock'){move(s,p,r.qty,'Customer return',r.id,r.date);p.serials.push(...r.serials.filter(n=>!p.serials.includes(n)));}s.warranties=s.warranties.map(w=>w.invoiceId===r.reference&&w.productId===r.productId&&(!r.serials.length||r.serials.includes(w.serial))?{...w,status:'Returned'}:w);}s.returns.unshift({...r,profit:r.type==='Customer'?null:0,status:refund<maxRefund?'Refund pending':'Completed'});if(refund>0)s.payments.unshift({id:uid('PAY'),date:r.date,direction:r.type==='Customer'?'Out':'In',account,amount:refund,purpose:r.type==='Customer'?'Customer refund':'Supplier refund',reference:r.reference,party:r.type==='Customer'?(original as Bill).customerId:(original as Purchase).supplierId,note:r.reason});log(s,'Return recorded',r.id);return s;}


